# TD App Mobile

Ce TD va vous permettre de prendre en main la gestion d'une App Mobile sur vos objets connectés.

Questions de cours:

1)

2)

3)

## Exercice 2 : Configuration + Hello World

Pour commencer, il faut telecharger le logiciel EvoThings sur votre pc et l'application CGTek Viewer sur votre télephone.

L'application Evothings va nous permettre de convertir notre code HTML CSS Javascript en Android.

Une fois le logiciel telechargé, rendez vous sur le lien suivant et suivre la partie "First time step-by-step guide" pour initier une connexion entre votre pc et votre smartphone.
https://evothings.com/doc/tutorials/evothings-studio-getting-started.html



## Exercice 3 (BONUS) :

1. Refaire le meme exercice en utilisant VisualStudioCode
